### ISSUE TITLE
Epic / Improve user accessibility

### ISSUE THREAD

**Issue by trisyoungs** [projectdissolve/epicbot#12]
### Focus
Improve user guides, access to them, and additional training material.

### Tasks
*Critical*
- [ ] #8 Update user documentation
- [ ] #10 Generate example data

*Medium Priority*
- [ ] #9 Fix links

### Notes
- [ ] Check web server!
